### PR TITLE
Update priority form designs

### PR DESCRIPTION
**Pull request by tzada8**
## Link to Ticket
https://trello.com/c/dKKhFS0t

## Brief Description of Changes
- Adjusted modal size depending on current screen size
- Added draggable icons
- Adjusted draggable functionality

## Checklist
- [X] I do not commit the .env file.
- [X] I added my changes to the appropriate frontend or backend folders.
- [X] All aspects of the ticket have been entirely addressed and completed.
- [X] Thorough automated tests have been added.
- [X] Functionality has been validated through manual tests.
- [ ] I have received approval from a peer before merging.

### CODE REVIEW

**Review by kprazuch — APPROVED** [review]
Looks good! The only note I have is on the priority dragging behaviour. If I move something from rank 5 to rank 1, I would expect everything above rank 5 to be pushed down one rank to make room at the top. But right now we have it so that the features in rank 5 and rank 1 get swapped, which I found confusing.

**Comment by tzada8** [comment]
Ohhh interesting, I had always thought of it as a swap functionality, but I like what your suggesting! I'll add it in this PR and let you know when you can re-review.

**Comment by tzada8** [comment]
Just updated now! Feel free to take a look and let me know your thoughts!

**Review by kprazuch — APPROVED** [review]
Awesome, looks good!

**Pull request merged**
