### PR TITLE
Clickable products

### PR DESCRIPTION
**Pull request by tzada8**
## Link to Ticket
https://trello.com/c/tvObxKc4

## Brief Description of Changes
- Add ability to select/deselect products
- Each selected product is stored in the React state (when deselected, product is removed from state)
- Removed previous temporary `/time` endpoint

NOTE: No idea why the spacing looks weird in GitHub (doesn't look like that locally)

## Checklist
- [X] I do not commit the .env file.
- [X] I added my changes to the appropriate frontend or backend folders.
- [X] All aspects of the ticket have been entirely addressed and completed.
- [ ] Thorough automated tests have been added.
- [X] Functionality has been validated through manual tests.
- [ ] I have received approval from a peer before merging.

### CODE REVIEW

**Comment by kprazuch** [comment]
How can I test this PR? This is what I see on the frontend but there doesn't seem to be an option to click products.
Screen Shot 2024-01-23 at 6 55 12 PM

**Comment by tzada8** [comment]
If you manually change the URL to `/product-search`, you should see it (I'll add links connecting the pages later on). Will add utests later on too (right now I just want to get the baseline functionality working)

Also, just as an FYI, you can see all frontend routes in the `App.js` file (similar to seeing all backend endpoints in `app.py`)

**Comment by kprazuch** [comment]
Sorry, I'm confused again. What should I be able to do on this screen? I can search but nothing is returned.
Screen Shot 2024-01-23 at 10 59 35 PM

**Comment by tzada8** [comment]
There's 2 things that might be causing this:

1. Some of the new packages haven't been installed for you locally. Try running `npm install` in the frontend folder
2. You're not running the backend at the same time. Since the frontend is calling endpoints from our backend, both services need to be running at the same time
    - one terminal in `backend` running `flask --debug run --no-debugger`
    - one terminal in `frontend` running `npm start`

**Review by kprazuch — APPROVED** [review]

**Pull request merged**
